[package]
name = "coppermoon_mysql"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "MySQL/MariaDB bindings for CopperMoon Lua runtime"

[dependencies]
mlua.workspace = true
thiserror.workspace = true

# MySQL driver
mysql = "25.0"
